### ISSUE TITLE
Preprocess on Megadepth dataset

### ISSUE THREAD

**Issue by RunyuZhu** [axelBarroso/ScaleNet#4]
thanks for your excellent work!
i have read your great paper and code, i wonder if you can share more code details about how to get the Ground Truth scale factor from Megadepth dataset. 
im fresh about processing dataset and i have met many problem. it will be so grateful if you can share me some experience
yours,
zhu

**Comment by axelBarroso** [comment]
Hello!

Thanks for the interest!

We detailed in Section 3.3 how we get the scale factor from image pairs (considering we have a point cloud). Which parts are unclear? If you could explain the problem you are facing, or give more details, I might be able to help? 

Thanks!

**Comment by RunyuZhu** [comment]
> Hello!
> 
> Thanks for the interest!
> 
> We detailed in Section 3.3 how we get the scale factor from image pairs (considering we have a point cloud). Which parts are unclear? If you could explain the problem you are facing, or give more details, I might be able to help?
> 
> Thanks!

I'm really appreciate for your reply, it's so kind of you !
I'm confused about the point cloud and its corresponding image pair;
you said "we identify the 3D points of the model that are visible in both images" at sec 3.3. i don't know how to make sure about which points are visible in both images.  
i found that file 'points3D.txt'  has **point3d_id & image_id & points2d_idx** attributes, and file 'images.txt' has  **image_id & point3d_id** which correspond to point's (x, y)  2d coordinate (both files are from Megadepth_sfm zip file). So did you retrieval co-vision 3d points by using IMAGE_ID attribute? and then calculate the ratio of 2d points distance between image pair as a Groud Truth scale factor like your paper said.
I'm sorry for my poor English grammar, and thanks for your patience
I'm looking forward for your reply!

Thanks!

**Comment by axelBarroso** [comment]
Hello!

During scale factor GT generation, we have access to the overlapping score between images. This overlapping score is just the ratio between mutual 3D points in images A and B and total 3D points in image A. 

We use the precomputed overlapping scores that tell us which images overlap and the 3D points visible from the two images. 

You can check how to use that information and get it from the LoFTR repository [here](https://github.com/zju3dv/LoFTR/blob/master/docs/TRAINING.md). 

Hope this helps. Thanks!
